Description: Provisions an s3 bucket with life cycle configuration and bucket encryption by default
Resources:
  # S3 bucket for clients
  NASFinancialClientsS3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: S3 bucket with default encryption
    Properties:
      BucketName:  NASclients-priv-data-bucket
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: '1825'
            Transitions:
              - TransitionInDays: 30
                StorageClass: GLACIER
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: KMS-KEY-ARN
    DeletionPolicy: Delete